# Generated by Django 3.2 on 2021-05-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django101', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
