# Generated by Django 3.2 on 2021-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0004_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2, max_length=2),
        ),
    ]
